import Head from 'next/head'
import Image from 'next/image'
import WhatToWatch from '../components/home/WhatToWatch'
import Reviews from '../components/home/Reviews';
import Recaps from '../components/home/Recaps';

import { client } from '../lib/client';




export default function Home({ shows, reviews, recaps }) {
	// console.log(recaps)

	return (
		<div className="">
			<Head>
				<title>Drama Decider</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<section className="my-16 max-w-lg md:max-w-2xl lg:max-w-5xl xl:max-w-7xl mx-auto">
					<h1 className="font-light text-lg md:text-3xl lg:text-5xl">
						<span className="font-bold font-notoSans text-xl md:text-4xl xl:text-6xl text-transparent bg-clip-text bg-gradient-to-br from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]">
							Welcome to Drama Decider.
						</span>{" "}
						See our thoughts, reviews, and recaps on the latest
						Korean Dramas to help you decide what to watch.
					</h1>
				</section>
				<section className="my-16">
					<WhatToWatch shows={shows} />
				</section>

				<section className="my-16 bg-orange-50">
					<Reviews reviews={reviews} />
				</section>
				<section className="my-16">
					<Recaps recaps={recaps} />
				</section>
			</main>
		</div>
	);
}

export const getServerSideProps = async () => {
	const showQuery = `*[_type == 'show']`;
	const shows = await client.fetch(showQuery);

	const reviewQuery = `*[_type == 'review']`;
	const reviews = await client.fetch(reviewQuery);

	const recapQuery = `*[_type == 'recap']`;
	const recaps = await client.fetch(recapQuery);


	return {
		props: {shows, reviews, recaps},
	};
};
